[Connection]
# Unique id for use in database.
# This should be traceable back
# to the physical device.
ICEFARM_WORKER_NAME =

# Port to host server on
ICEFARM_SERVER_PORT = 8081

# ip clients should use to reach this
# worker - this needs to be accessible.
# This is typically, but not necessarily,
# just the ip of the device.
ICEFARM_VIRTUAL_IP =
# Port clients should use to reach this worker.
# This is typically, but not necessarily,
# the same as SERVER_PORT.
ICEFARM_VIRTUAL_PORT = 8081

# Url to the control server
ICEFARM_CONTROL_SERVER =

# NOTE
# This is a libpq (https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING)
# connection string for database access. It must be set as an environment variable.
# ICEFARM_DATABASE

# All other configuration options can be set instead as environment variables.
# If a config is specified, those options take precedence over the environment
# variables.

[Firmware]
ICEFARM_DEFAULT = firmware/default/build/default_firmware.uf2
ICEFARM_PULSE_COUNT = firmware/pulse_count/build/bitstream_over_usb.uf2